spring:
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/guarantee_tracking
    username: ${DB_USERNAME:guarantee-user}
    password: ${DB_PASSWORD:guarantee-password}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true